In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [3]:
l = [1, 2,3 ,4 ,5 ,6 ]

In [4]:
arr = np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [9]:
np.array()

array([1, 2, 4])

In [10]:
l2d = [[1, 2,3], [4, 5, 6], [7, 8, 9]]

In [11]:
arr2d = np.array(l2d)

In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2d.shape

(3, 3)

In [16]:
np.arange(10, 20,  2)

array([10, 12, 14, 16, 18])

In [19]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
x = np.ones((5,  4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
x[3][2]

1.0

In [27]:
x[3, 2] = 99

In [28]:
x

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1., 99.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [32]:
np.ones((5,  4))*2+7

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [35]:
x = np.ones((3, 4, 5))

In [36]:
x.shape

(3, 4, 5)

In [39]:
x.reshape((5, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [41]:
x.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
x = np.eye(6)
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [46]:
y = np.ones((6,6))

In [47]:
y == x

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True]])

In [48]:
y = y*3

In [50]:
y.dot(x)

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [54]:
np.cross(x, y)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [57]:
x.shape

(6, 6)

In [59]:
y.shape

(6, 6)

In [63]:
x = np.arange(30)

In [64]:
x = x.reshape((5, 6))

In [68]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [69]:
x.mean()

14.5

In [72]:
sum(sum(x))/30

14.5

In [73]:
x.std()

8.65544144839919

In [76]:
x.mean(axis = 0) # columns wise

array([12., 13., 14., 15., 16., 17.])

In [77]:
x.std(axis = 1)

array([1.70782513, 1.70782513, 1.70782513, 1.70782513, 1.70782513])

In [79]:
x.mean(axis =1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

In [92]:
np.log(x)

C:\Users\Akash\Anaconda3\envs\rootenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
        2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872,
        2.83321334],
       [2.89037176, 2.94443898, 2.99573227, 3.04452244, 3.09104245,
        3.13549422],
       [3.17805383, 3.21887582, 3.25809654, 3.29583687, 3.33220451,
        3.36729583]])

In [88]:
import math

In [91]:
math.log(144, 12)

2.0

In [102]:
np.random.rand(10)*5+5

array([5.59014539, 6.14940154, 6.55864334, 9.0883563 , 7.39367509,
       7.92325254, 9.90529217, 6.73367984, 8.05571299, 5.05926377])

In [123]:
np.random.seed(20)
np.random.randint(1, 100, (3, 4))

array([[91, 16, 96, 29],
       [91, 10, 21, 76],
       [23, 72, 35, 97]])

In [124]:
np.random.randint(1, 100, (3, 4))

array([[41, 86, 91, 27],
       [84, 17, 63, 17],
       [ 8, 99,  7, 27]])

In [125]:
arr = np.arange(18)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [126]:
np.random.shuffle(arr)

In [127]:
arr

array([ 8,  4,  1,  5,  7,  6, 12,  2,  0, 14, 17, 16, 15,  3,  9, 10, 11,
       13])

In [128]:
arr.min()

0

In [129]:
arr.max()

17

In [130]:
arr.argmin()

8

In [132]:
arr.argmax()

10

In [134]:
arr.sort()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [137]:
np.linspace(0,  10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [ ]:
np.random.